import { SentinelOneAgent } from "../sentinelone/types";
import { createAgentEntities } from "./agents";

test("convert agent entity", () => {
  const agents: SentinelOneAgent[] = [
    {
      domain: "domain",
      appsVulnerabilityStatus: "appsVulnerabilityStatus",
      siteName: "siteName",
      coreCount: 1,
      totalMemory: 2,
      inRemoteShellSession: true,
      osArch: "osArch",
      allowRemoteShell: true,
      scanStatus: "scanStatus",
      consoleMigrationStatus: "consoleMigrationStatus",
      updatedAt: "2019-04-22T21:43:53.000Z",
      osType: "osType",
      id: "id",
      createdAt: "2019-04-22T21:43:53.000Z",
      externalIp: "externalIp",
      computerName: "computerName",
      modelName: "modelName",
      uuid: "uuid",
      encryptedApplications: true,
      adComputerDistinguishedName: "adComputerDistinguishedName",
      osUsername: "osUsername",
      groupName: "groupName",
      infected: true,
      policyUpdatedAt: "2019-04-22T21:43:53.000Z",
      cpuId: "cpuId",
      registeredAt: "2019-04-22T21:43:53.000Z",
      activeThreats: 3,
      groupUpdatedAt: "2019-04-22T21:43:53.000Z",
      machineType: "machineType",
      groupIp: "groupIp",
      osStartTime: "2019-04-22T21:43:53.000Z",
      osRevision: "osRevision",
      scanAbortedAt: "2019-04-22T21:43:53.000Z",
      siteId: "siteId",
      scanStartedAt: "2019-04-22T21:43:53.000Z",
      isPendingUninstall: true,
      scanFinishedAt: "2019-04-22T21:43:53.000Z",
      lastActiveDate: "2019-04-22T21:43:53.000Z",
      groupId: "groupId",
      isActive: true,
      agentVersion: "agentVersion",
      licenseKey: "licenseKey",
      networkStatus: "networkStatus",
      lastLoggedInUserName: "lastLoggedInUserName",
      osName: "osName",
      mitigationMode: "mitigationMode",
      cpuCount: 4,
      isUninstalled: false,
      isUpToDate: true,
      mitigationModeSuspicious: "mitigationModeSuspicious",
      isDecommissioned: false,
    },
  ];
  expect(createAgentEntities(agents)).toEqual([
    {
      _class: "HostAgent",
      _key: "sentinelone_agent-id-id",
      _type: "sentinelone_agent",
      activeThreats: 3,
      adComputerDistinguishedName: "adComputerDistinguishedName",
      agentVersion: "agentVersion",
      allowRemoteShell: true,
      appsVulnerabilityStatus: "appsVulnerabilityStatus",
      computerName: "computerName",
      consoleMigrationStatus: "consoleMigrationStatus",
      coreCount: 1,
      cpuCount: 4,
      cpuId: "cpuId",
      createdAt: 1555969433000,
      displayName: "computerName",
      domain: "domain",
      encryptedApplications: true,
      externalIp: "externalIp",
      groupId: "groupId",
      groupIp: "groupIp",
      groupName: "groupName",
      groupUpdatedAt: 1555969433000,
      id: "id",
      inRemoteShellSession: true,
      infected: true,
      isActive: true,
      isDecommissioned: false,
      isPendingUninstall: true,
      isUninstalled: false,
      isUpToDate: true,
      lastActiveDate: 1555969433000,
      lastLoggedInUserName: "lastLoggedInUserName",
      licenseKey: "licenseKey",
      machineType: "machineType",
      mitigationMode: "mitigationMode",
      mitigationModeSuspicious: "mitigationModeSuspicious",
      modelName: "modelName",
      networkStatus: "networkStatus",
      osArch: "osArch",
      osName: "osName",
      osRevision: "osRevision",
      osStartTime: 1555969433000,
      osType: "osType",
      osUsername: "osUsername",
      policyUpdatedAt: 1555969433000,
      registeredAt: 1555969433000,
      scanAbortedAt: 1555969433000,
      scanFinishedAt: 1555969433000,
      scanStartedAt: 1555969433000,
      scanStatus: "scanStatus",
      siteId: "siteId",
      siteName: "siteName",
      totalMemory: 2,
      updatedAt: 1555969433000,
      uuid: "uuid",
    },
  ]);
});
