import { SentinelOneAgent } from "../sentinelone/types";
import { AgentEntity } from "../types";

export const AGENT_ENTITY_TYPE = "sentinelone_agent";
export const AGENT_ENTITY_CLASS = "HostAgent";

export function createAgentEntities(data: SentinelOneAgent[]): AgentEntity[] {
  return data.map(d => ({
    _key: `${AGENT_ENTITY_TYPE}-id-${d.id}`,
    _type: AGENT_ENTITY_TYPE,
    _class: AGENT_ENTITY_CLASS,
    displayName: d.computerName,
    domain: d.domain,
    appsVulnerabilityStatus: d.appsVulnerabilityStatus,
    siteName: d.siteName,
    coreCount: d.coreCount,
    totalMemory: d.totalMemory,
    inRemoteShellSession: d.inRemoteShellSession,
    osArch: d.osArch,
    allowRemoteShell: d.allowRemoteShell,
    scanStatus: d.scanStatus,
    consoleMigrationStatus: d.consoleMigrationStatus,
    updatedAt: d.updatedAt,
    osType: d.osType,
    id: d.id,
    createdAt: d.createdAt,
    externalIp: d.externalIp,
    computerName: d.computerName,
    modelName: d.modelName,
    uuid: d.uuid,
    encryptedApplications: d.encryptedApplications,
    adComputerDistinguishedName: d.adComputerDistinguishedName,
    osUsername: d.osUsername,
    groupName: d.groupName,
    infected: d.infected,
    policyUpdatedAt: d.policyUpdatedAt,
    cpuId: d.cpuId,
    registeredAt: d.registeredAt,
    activeThreats: d.activeThreats,
    groupUpdatedAt: d.groupUpdatedAt,
    machineType: d.machineType,
    groupIp: d.groupIp,
    osStartTime: d.osStartTime,
    osRevision: d.osRevision,
    scanAbortedAt: d.scanAbortedAt,
    siteId: d.siteId,
    scanStartedAt: d.scanStartedAt,
    isPendingUninstall: d.isPendingUninstall,
    scanFinishedAt: d.scanFinishedAt,
    lastActiveDate: d.lastActiveDate,
    groupId: d.groupId,
    isActive: d.isActive,
    agentVersion: d.agentVersion,
    licenseKey: d.licenseKey,
    networkStatus: d.networkStatus,
    lastLoggedInUserName: d.lastLoggedInUserName,
    osName: d.osName,
    mitigationMode: d.mitigationMode,
    cpuCount: d.cpuCount,
    isUninstalled: d.isUninstalled,
    isUpToDate: d.isUpToDate,
    mitigationModeSuspicious: d.mitigationModeSuspicious,
    isDecommissioned: d.isDecommissioned,
  }));
}
